%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\david\Documents\Universidad\Master\Thesis\thesis\MATLAB\beamConsts.csv
%
% Auto-generated by MATLAB on 15-Apr-2025 09:59:57

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = [1, 16];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
dbf_params_fp = readtable("C:\Users\david\Documents\Universidad\Master\Thesis\thesis\MATLAB\beamConsts.csv", opts);

%% Convert to output type
dbf_params_fp = table2array(dbf_params_fp);

%% Clear temporary variables
clear opts